rotors <- c("I", "II", "III", "IV", "V", "VI", "VII", "VIII", "VIIII")

fluidPage(
  title = 'EmigmulatoR',

      # create some select inputs
        h2("Enigma Settings"),
        fluidRow(
          column(3,  h4("Reflector", align = "right", style="padding:15px;")),
          column(2,selectInput("reflector", "",
                               choices = c("B", "C")))
        ),
        fluidRow(
          column(3, align = "right", h4("Rotors", style="padding:15px;")),
          column(2, align = "center",
                 selectInput("rotor1", "1",
                 choices = rotors)),
          column(2, align = "center",
                 selectInput("rotor2", "2",
                               choices = rotors)),
          column(2, align = "center",
                 selectInput("rotor3", "3",
                               choices = rotors))
          ),
        fluidRow(
          column(3, align = "right", h4("Ring Settings", style="padding:15px;")),
          column(2,selectInput("setting1", "",
                               choices = LETTERS)),
          column(2,selectInput("setting2", "",
                               choices = LETTERS)),
          column(2,selectInput("setting3", "",
                               choices = LETTERS))
        ),
        fluidRow(
          column(3, align = "right", h4("Start Positions", style="padding:15px;")),
          column(2,selectInput("position1", "",
                               choices = LETTERS)),
          column(2,selectInput("position2", "",
                               choices = LETTERS)),
          column(2,selectInput("position3", "",
                               choices = LETTERS))
        ),
        fluidRow(
          column(12, align = "center",
                 h4("Plugboard"))
          ),
    
        fluidRow(
          column(1, offset = 2, 
                 selectInput("p_A", "A",
                              selected = "",
                              selectize = FALSE,
                              choices = c("", LETTERS))),
          column(1,selectInput("p_B", "B",
                               selected = "",
                               selectize = FALSE,
                               choices = c("", LETTERS))),
          column(1,selectInput("p_C", "C",
                               selected = "",
                               selectize = FALSE,
                               choices = c("", LETTERS))),
          column(1,selectInput("p_D", "D",
                               selected = "",
                               selectize = FALSE,
                               choices = c("", LETTERS))),
          column(1,selectInput("p_E", "E",
                               selected = "",
                               selectize = FALSE,
                               choices = c("", LETTERS))),
          column(1,selectInput("p_F", "F",
                               selected = "",
                               selectize = FALSE,
                               choices = c("", LETTERS))),
          column(1,selectInput("p_G", "G",
                               selected = "",
                               selectize = FALSE,
                               choices = c("", LETTERS))),
          column(1,selectInput("p_H", "H",
                               selected = "",
                               selectize = FALSE,
                               choices = c("", LETTERS)))
        ),
        fluidRow(
          column(1, offset = 2, 
                 selectInput("p_I", "I",
                             selected = "",
                             selectize = FALSE,
                             choices = c("",LETTERS))),
          column(1,selectInput("p_J", "J",
                               selected = "",
                               selectize = FALSE,
                               choices = c("", LETTERS))),
          column(1,selectInput("p_K", "K",
                               selected = "",
                               selectize = FALSE,
                               choices = c("", LETTERS))),
          column(1,selectInput("p_L", "L",
                               selected = "",
                               selectize = FALSE,
                               choices = c("", LETTERS))),
          column(1,selectInput("p_M", "M",
                               selected = "",
                               selectize = FALSE,
                               choices = c("", LETTERS))),
          column(1,selectInput("p_N", "N",
                               selected = "",
                               selectize = FALSE,
                               choices = c("", LETTERS))),
          column(1,selectInput("p_O", "O",
                               selected = "",
                               selectize = FALSE,
                               choices = c("", LETTERS))),
          column(1,selectInput("p_P", "P",
                               selected = "",
                               selectize = FALSE,
                               choices = c("", LETTERS)))
        ),
        fluidRow(
          column(1, offset = 2, 
                 selectInput("p_Q", "Q",
                             selected = "",
                             selectize = FALSE,
                             choices = c("", LETTERS))),
          column(1,selectInput("p_R", "R",
                               selectize = FALSE,
                               selected = "",
                               choices = c("", LETTERS))),
          column(1,selectInput("p_S", "S",
                               selectize = FALSE,
                               selected = "",
                               choices = c("", LETTERS))),
          column(1,selectInput("p_T", "T",
                               selectize = FALSE,
                               selected = "",
                               choices = c("", LETTERS))),
          column(1,selectInput("p_U", "U",
                               selectize = FALSE,
                               selected = "",
                               choices = c("", LETTERS))),
          column(1,selectInput("p_V", "V",
                               selected = "",
                               selectize = FALSE,
                               choices = c("", LETTERS))),
          column(1,selectInput("p_W", "W",
                               selectize = FALSE,
                               selected = "",
                               choices = c("", LETTERS))),
          column(1,selectInput("p_X", "X",
                               selectize = FALSE,
                               selected = "",
                               choices = c("", LETTERS)))
        ),
        fluidRow(
          column(1, offset = 5, 
                 selectInput("p_Y", "Y",
                             selected = "",
                             selectize = FALSE,
                             choices = c("", LETTERS))),
          column(1,selectInput("p_Z", "Z",
                               selected = "",
                               selectize = FALSE,
                               choices = c("", LETTERS)))
        ),
        fluidRow(
          column(12, align = "center",
                 textAreaInput("textInput", "Input", value = ""))
        ),
        fluidRow(
          column(4, align = "center", offset=4,
                 h5(HTML("<b>Output<b>")),
                 verbatimTextOutput("textOutput", placeholder = TRUE))
        )
  
      )
